[package]
name = "coolstyleserver"
version = "1.2.1"
edition = "2021"
license = "MIT"
authors = ["Erick Merchant <erickmerchant@gmail.com>"]
description = "a proxy server for stylesheet hot reloading"
homepage = "https://github.com/erickmerchant/coolstyleserver"
documentation = "https://github.com/erickmerchant/coolstyleserver"
repository = "https://github.com/erickmerchant/coolstyleserver.git"
readme = "README.md"
keywords = ["css", "hmr"]

[dependencies]
anyhow = { version = "1.0.70", features = ["backtrace"] }
axum = "0.6.15"
async-stream = "0.3.5"
lol_html = "1.0.0"
tokio = { version = "1.27.0", features = ["macros", "rt-multi-thread"] }
hyper = { version = "0.14.27", features = ["client"] }
futures = "0.3.28"
notify = "6.0.1"
serde = "1.0.171"
serde_json = "1.0.100"
pathdiff = "0.2.1"
clap = { version = "4.3.11", features = ["derive"] }
camino = "1.1.6"

[profile.release]
strip = true
lto = true
